import { Case, CaseListItem } from './api/client';

export const MOCK_CASES: CaseListItem[] = [
    {
        id: 'case-1',
        entityName: 'Acme Corp',
        riskTier: 'Lower Risk',
        assignedUser: 'John Doe',
        status: 'ONBOARDING_COMPLETE',
        businessUnit: 'Ardonagh Specialty',
        roleType: 'Corporate',
        daysOpen: 5,
        daysSinceLastCustomerTouchpoint: 2,
        lastUpdated: new Date().toISOString(),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'case-2',
        entityName: 'Globex Inc',
        riskTier: 'Higher Risk',
        assignedUser: 'Jane Smith',
        status: 'AWAITING_KYC_REVIEW',
        businessUnit: 'Price Forbes',
        roleType: 'Corporate',
        daysOpen: 12,
        daysSinceLastCustomerTouchpoint: 10,
        lastUpdated: new Date().toISOString(),
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'case-3',
        entityName: 'Soylent Corp',
        riskTier: 'Higher Risk',
        assignedUser: 'Alice Johnson',
        status: 'FINANCIAL_CRIME_REVIEW',
        businessUnit: 'Bishopsgate',
        roleType: 'Corporate',
        daysOpen: 45,
        daysSinceLastCustomerTouchpoint: 1,
        lastUpdated: new Date().toISOString(),
        createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

export const MOCK_CASE_DETAILS: Record<string, Case> = {
    'case-1': {
        _id: 'case-1',
        entityName: 'Acme Corp',
        status: 'ONBOARDING_COMPLETE',
        riskTier: 'Lower Risk',
        cpiScore: 10,
        daysOpen: 5,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdated: new Date().toISOString(),
        assignedUser: 'John Doe',
        businessUnit: 'Ardonagh Specialty',
        beForm: {
            legalName: 'Acme Corp',
            tradingName: 'Acme',
            country: 'UK',
            roleType: 'Corporate',
            addressLine1: '123 Main St',
            city: 'London',
            postcode: 'SW1A 1AA',
            registrationNumber: '12345678',
            customerType: 'Medium',
            statementEmail: 'accounts@acme.com',
            creditControllerEmail: 'credit@acme.com',
            bankDetailsRequired: false,
        },
        automationResults: {
            companiesHouse: { status: 'success', data: null, message: null },
            fca: { status: 'pending', data: null, message: null },
            dAndB: { status: 'pending', data: null, message: null },
            lexisNexis: { status: 'pending', data: null, message: null },
        },
        attachments: [],
    },
    'case-2': {
        _id: 'case-2',
        entityName: 'Globex Inc',
        status: 'AWAITING_KYC_REVIEW',
        riskTier: 'Higher Risk',
        cpiScore: 85,
        daysOpen: 12,
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdated: new Date().toISOString(),
        assignedUser: 'Jane Smith',
        businessUnit: 'Price Forbes',
        beForm: {
            legalName: 'Globex Inc',
            tradingName: 'Globex',
            country: 'USA',
            roleType: 'Corporate',
            addressLine1: '456 Elm St',
            city: 'New York',
            postcode: '10001',
            registrationNumber: '98765432',
            customerType: 'Large',
            statementEmail: 'accounts@globex.com',
            creditControllerEmail: 'credit@globex.com',
            bankDetailsRequired: true,
        },
        automationResults: {
            companiesHouse: { status: 'success', data: null, message: null },
            fca: { status: 'failed', data: null, message: 'Not found' },
            dAndB: { status: 'success', data: null, message: null },
            lexisNexis: { status: 'pending', data: null, message: null },
        },
        attachments: [
            {
                id: 'att-1',
                fileName: 'ci_certificate.pdf',
                fileType: 'PDF',
                source: 'manual',
                uploadedAt: new Date().toISOString(),
                uploadedBy: 'system',
                downloadUrl: '#',
                lastUpdatedAt: new Date().toISOString()
            }
        ],
    },
};
